#!/bin/bash

# some shit script that i'm writing which acts as a "ctrl+alt+del on Windows" equivalent,
# giving me all the shit i need like changing themes, logging out, etc.

areyousure () {
	u=$(printf "no\nyes" | rofi -dmenu -p "are you sure?" -l 2 -width 10)
	if [ "$u" = "yes" ]; then
		return 0
	else
		return 1
	fi
}

sel=$(printf "change theme\nlogout\nshutdown" | rofi -dmenu -p "what do you want to do?" -l 3 -width 15)
if [ "$sel" = "change theme" ]; then
	a=$(wpg -l | sed -e 's/-/ /g' | awk -F '\\.*' '{print $1}' | rofi -dmenu -p "what theme?" -width 15)
	b=$(echo $a | sed -e 's/ /-/g')
	c=$(wpg -l | grep $b)
	wpg -s $c

elif [ "$sel" = "logout" ]; then
	areyousure
	if [[ $? -eq 0 ]]; then
		i3-msg exit
	fi

elif [ "$sel" = "shutdown" ]; then
	areyousure
	if [[ $? -eq 0 ]]; then
		/usr/sbin/shutdown now
	fi
fi